#import <Foundation/Foundation.h>

#define BMSTRINGSFILECHECK_ERROR_NO_ERROR												0

#define BMSTRINGSFILECHECK_ERROR_REACHED_END_OF_STRING_WHILE_PARSING_QUOTED_STRING		1

#define BMSTRINGSFILECHECK_ERROR_REACHED_END_OF_STRING_IN_COMMENT						2

#define BMSTRINGSFILECHECK_ERROR_REACHED_END_OF_STRING									3


#define BMSTRINGSFILECHECK_ERROR_MISSING_FINAL_SEMICOLON								4

#define BMSTRINGSFILECHECK_ERROR_UNEXPECTED_CHARACTER_SEMICOLON_WANTED					5

#define BMSTRINGSFILECHECK_ERROR_UNEXPECTED_CHARACTER_EQUAL_OR_SEMICOLON_WANTED			6

#define BMSTRINGSFILECHECK_ERROR_INCOMPLETE_ENTRY										7

#define BMSTRINGSFILECHECK_ERROR_INVALID_UTF8_DATA										8

#define BMSTRINGSFILECHECK_ERROR_MISSGING_OPENING_QUOTE									9

@interface BMStringsFileChecker : NSObject
{
	id delegate;
	
	NSString * path_;
}

+ (id) stringsFileChecker;

- (BOOL) parseString:(NSString *) inString;

- (BOOL) checkStringsFileAtPath:(NSString *) inPath withDelegate:(id) inDelegate;


@end
